name: Build and Deploy docs

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Check out the repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2) Install Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      # 3) Install deps
      - name: Install dependencies
        run: npm install

      # 4) Build into docs/
      - name: Build
        run: npm run build

      # 5) Commit & push docs/
      - name: Commit docs/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "chore: build docs/ [skip ci]" || echo "No changes to commit"
          git push
